# Generated by Django 4.2.4 on 2023-09-05 16:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='author',
            field=models.CharField(default='Неизвестный автор', max_length=20),
        ),
        migrations.AddField(
            model_name='article',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2023, 9, 5, 19, 32, 40, 778471)),
        ),
        migrations.AddField(
            model_name='article',
            name='description',
            field=models.TextField(default='Статья в разработке'),
        ),
        migrations.AddField(
            model_name='article',
            name='title',
            field=models.CharField(default='Без названия', max_length=30),
        ),
    ]
