# Generated by Django 4.2.4 on 2023-09-07 16:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0003_alter_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='mailingaddress',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='article',
            name='date',
            field=models.DateField(default=datetime.date(2023, 9, 7)),
        ),
    ]
