# Generated by Django 4.2.4 on 2023-09-07 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0004_mailingaddress_email_alter_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='pesron',
            name='city',
            field=models.CharField(default='Неизвестно', max_length=30),
        ),
        migrations.AddField(
            model_name='pesron',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='pesron',
            name='name',
            field=models.CharField(default='Неизвестно', max_length=30),
        ),
        migrations.AddField(
            model_name='pesron',
            name='phone',
            field=models.CharField(default='Неизвестно', max_length=17),
        ),
        migrations.AddField(
            model_name='pesron',
            name='surname',
            field=models.CharField(default='Неизвестно', max_length=30),
        ),
    ]
