# Generated by Django 4.2.4 on 2023-09-07 17:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0005_pesron_city_pesron_email_pesron_name_pesron_phone_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Pesron',
            new_name='Person',
        ),
    ]
