# Generated by Django 4.2.4 on 2023-09-07 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0006_rename_pesron_person'),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login', models.CharField(default='Неизвестно', max_length=30)),
                ('password', models.CharField(default='Неизвестно', max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='ArticlesThemes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Theme',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
