# Generated by Django 4.2.4 on 2023-09-12 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0008_alter_article_author_alter_article_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='account',
            name='person',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to='new_app.person'),
        ),
        migrations.AlterField(
            model_name='article',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='new_app.person'),
        ),
    ]
