# Generated by Django 4.2.4 on 2023-09-12 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0009_account_person_alter_article_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='theme',
            field=models.ManyToManyField(to='new_app.theme'),
        ),
        migrations.AddField(
            model_name='theme',
            name='name',
            field=models.CharField(default='Без названия', max_length=30),
        ),
    ]
