# Generated by Django 4.2.4 on 2023-09-12 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('new_app', '0011_remove_article_theme'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='theme',
            field=models.ManyToManyField(to='new_app.theme'),
        ),
    ]
